visualizer_path: "C:/Users/sashk/AppData/Roaming/fnm/node-versions/v22.11.0/installation/mmdc.cmd"
package: "openssl"
repo_url: "http://archive.ubuntu.com/ubuntu/dists/focal/main/binary-amd64/Packages.gz"